### ISSUE TITLE
Deliver page content by separate endpoint

### ISSUE THREAD

**Issue by rossjrw** [pxdnbluesoul/scuttle#23]
Currently `/page/{id}` delivers all the content of a page, including its metadata and content. I'm a little concerned about waiting times for applications where the page content isn't needed.

Wikidot takes this approach by splitting their endpoint into `get_page` and `get_metadata`, and then uses the reduced data requirement for `get_metadata` to allow querying multiple pages at once. It's possible that this is the only thing that Wikidot does sort of okay.

I wonder if SCUTTLE might be able to take a similar approach? If not for efficiency in collecting metadata, then at least only requesting page content when it is needed? I'm thinking that revision content could be moved entirely to the revisions endpoint.

**Comment by danieltharp** [comment]
https://scuttle.atlassian.net/browse/API-16
